import "./globals.css";
import "./assets/css/signup-variables.css";
import "./assets/css/signup.css";
import "./assets/css/dashboard.css";
import "./assets/css/patient-login.css";
import "./assets/css/admin.css"
import { NavigationProvider, NavigationLoader } from './[lng]/components/common/loaders';
import AuthProvider from "./auth/auth-session-provider";
export const metadata = {
  title: "Dochyve Super Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        
        <NavigationProvider>
          <AuthProvider>
          {children}
          </AuthProvider>
          <NavigationLoader />
        </NavigationProvider>
      </body>
    </html>
  );
}
